### PR TITLE
Support storing password in SecretService keyring

### PR DESCRIPTION
**Pull request by Jmennius**
That should be a bit safer that storing the password in plain text, at least for my OCD 😄 
Needs testing with docker (I've tested with podman).

- [ ] test with docker

### CODE REVIEW

**Review by netbrain — COMMENTED** [review]
Looks good to me, @sHedC any input? 

My only concern is that the complexity we keep adding will make it undoubtedly harder to support and change in the future.

**Comment by sHedC** [comment]
> Looks good to me, @sHedC any input?
> 
> My only concern is that the complexity we keep adding will make it undoubtedly harder to support and change in the future.

Yes, but I think it is probably a good idea for those people who do not encrypt drives.  But what about regression for those with password already set.

I will check this out and test against podman and docker.

**Comment by Jmennius** [comment]
So I've recently learned that `docker secret` is not available in regular docker:
```
docker secret ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.                                                               
```
This basically means that implementation for docker is broken at the moment.

**Comment by netbrain** [comment]
Should probably add this clarification in the readme.

**Pull request merged**
