### PR TITLE
Update to Support zwo files better and other Minor Fixes.

### PR DESCRIPTION
**Pull request by sHedC**
Some additional fixes below, this requires a rebuild of the docker.

- #89 Added the abiltiy to map a directory for custom zwo files to a local directory using an environment parameter, updated readme.
- Minor Fix to Docker to make the entrypoint and other files rx by default (from just x)
- Minor Fix for Podman Build to set ipc host temporarily, can cause failures on laptops
- #147 - Attempt to fix issue by moving the Enviornment Variables for NVIDIA
- Update Readme to point to new Nvidia-container-toolkit not the deprecated one

### CODE REVIEW

**Review by netbrain — APPROVED** [review]

**Comment by netbrain** [comment]
Looks good. 👍

**Comment by sHedC** [comment]
Added minor update to the ZWO section to talk about the subfolder and internal zwift id.

**Comment by sHedC** [comment]
@netbrain -  FYI, Build is failing since last night due to some dependency in Wine that is blocked.  Stable and Devel branches.

**Review by netbrain — APPROVED** [review]

**Comment by netbrain** [comment]
Ok, you need anything from me?

**Comment by sHedC** [comment]
> Ok, you need anything from me?

No its broken at the wine side, there is already an issue related.  Just informing as you can't merge this request because build fails.  I think something to do with related updates where the 64 and 32 bit library versons are conflicting.

I noticed as I was testng a new zwift builder workflow started failing last night.

Once fixed I will merge and build :)

**Comment by sHedC** [comment]
@netbrain - Trixie build still borked, due to issues between the 386 and 64 dependancies.  It builds and runs with Bookworm but Nvidia using Experimental Wayland is stuffed in bookworm (no idea why).

Guess either wait for trixie to be fixed or note that Nvidia can't run in Wayland experimental mode.  To be fair Nvidia under wayland is not good anyway as eventually the NVRAM fills and programs crash.

**Pull request merged**
