### PR TITLE
feat: use gamemode for screensaver inhibit

### PR DESCRIPTION
**Pull request by perrin4869**
This is an alternative to https://github.com/netbrain/zwift/pull/148
The main concern is that this may not work for someone running mate or cinnamon, but can't tell for sure without trying it out or digging into their source code...

### CODE REVIEW

**Comment by sHedC** [comment]
I will  run tests to day on a few of my VM's. Learning how to checkout and test PR's :)

**Comment by sHedC** [comment]
have an issue with Wayland but not sure what it is yet so testing.

**Review by sHedC — CHANGES_REQUESTED** [review]
In the Docker File, Wine running experimental wayland needs the xdg-utils installed, can you re-add that component for Wine Wayland please.

**Comment by perrin4869** [comment]
Wow that's interesting! Thanks for testing 😀 
I'll update the PR tomorrow
Btw, do you know which program from xdg-utils is needed by experimental Wayland? Wonder why it isn't a dependency of the package

**Comment by sHedC** [comment]
Um no i will see if I can find out. It just complains that the wrong
version of opengl so will check the wine forum

**Comment by sHedC** [comment]
as far as I can tell it uses xdg-open but maybe also xdg-runtime.

**Comment by sHedC** [comment]
Testing

- [ ] Fedora 40 Gnome X11
- [ ] Fedora 40 Gnome Wayland (both X11 and Wayland Experimental)
- [X] Mint 21 - Cinnamon (whatever is default)
- [ ] Nobara 39 KDE (Wayland)

**Comment by sHedC** [comment]
Tested what I can seems to work fine, let me know when you have re-added xdg-utils.

**Comment by perrin4869** [comment]
Ok, added `xdg-utils` back. I'm wondering if maybe this is a bug in the dependencies on the Ubuntu package side though

**Comment by sHedC** [comment]
> Ok, added `xdg-utils` back. I'm wondering if maybe this is a bug in the dependencies on the Ubuntu package side though

I think that wine wayland is depending on xdg-shell maybe, but then I am not that into wine dev to know, I did find this which is an read: https://bugaevc.gitbooks.io/writing-wayland-clients/content/beyond-the-black-square/xdg-shell.html

**Review by sHedC — APPROVED** [review]
Looks good for me

**Comment by sHedC** [comment]
@netbrain - I have reviewed and tested this seems to be good for both screen saver/ power management and performance in all my tests.

**Review by netbrain — APPROVED** [review]

**Comment by netbrain** [comment]
Looks good! Great work

**Pull request merged**
