### PR TITLE
Back to debian in order to support nvidia cards

### PR DESCRIPTION
**Pull request by netbrain**

### CODE REVIEW

**Comment by cmuench** [comment]
@netbrain 
Just created a docker image by using this branch.
Looks good on my machine with Nvidia driver.
Runs smooth in 4K.

:+1: 

grafik

**Comment by cmuench** [comment]
@netbrain It's running but I have a strange new effect. If I exit the game, the container still runs in the background.
Seems that the applicartion is not stopping.
Maybe only on my machine?
Would be nice if someone else can test the branch, too.

I see this in the logs:

```
+ pgrep -f ZwiftApp.exe
+ echo 'Killing uneccesary applications'
+ pkill ZwiftLauncher
Killing uneccesary applications
+ pkill ZwiftWindowsCra
+ wineserver -w
021c:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher"
wine: Call from 00006FFFFF463DF7 to unimplemented function combase.dll.RoUnregisterForApartmentShutdown, aborting
021c:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementWatcher"
wine: Call from 00006FFFFF463DF7 to unimplemented function combase.dll.RoUnregisterForApartmentShutdown, aborting
```

**Comment by gallais** [comment]
@cmuench Don't know about it not stopping but I did notice my laptop becoming extremely slow after leaving 1.62.0 yesterday. I ended up rebooting the machine just to be able to open firefox. :thinking:

**Comment by netbrain** [comment]
Can confirm the issue of the container not stopping. seems MicrosoftEdgeUpdate is preventing the wineserver from shutting down. Killing it on zwift startup instead.

**Pull request merged**
